name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.8.1
      - name: Install package
        run: yarn install
      - name: Building package
        run: yarn build
      - name: Deploying pages
        run: yarn deploy
    
